Fix moc error cause can't find interface
qdeclarativefolderlistmodel.h(56): Error: Undefined interface

class QDeclarativeFolderListModel : public QAbstractListModel, public
QDeclarativeParserStatus
{
    Q_OBJECT
    Q_INTERFACES(QDeclarativeParserStatus)

Change-Id: I878e0bfb32627816e89c80c04a39cdc4c1fb2038